require('./../scss/style.scss')
require('./components/background.js')
require('./components/contact.js')
require('./components/link-blocks.js')
require('./components/map.js')
require('./components/menu.js')
